general:
  systems:
  - name: methanol
    components:
    - smiles: '[C:1]([H:3])([H:4])([H:5])[O:2][H:6]'
      nmol: 350
    weight: 1.0
  force_field_name: de-force-1.0.3.offxml
  mlp_name: mace-off24-medium
  output_dir: output
simulation:
  temperature: 300 K
  pressure: 1.0 atm
  timestep: 1.0 fs
  n_minimization_steps: 0
  n_equilibration_nvt_steps: 50000
  n_equilibration_npt_steps: 50000
  n_production_steps: 1000000
  n_mlp_steps: 0
  mlp_device: cpu
  platform: CPU
  report_interval: 2000
scaling:
  close_range:
  - 0.75
  - 0.9
  - 5
  equilibrium_range:
  - 0.9
  - 1.1
  - 15
  long_range:
  - 1.1
  - 2.0
  - 12
  subsample_frequency: 20
training:
  learning_rate: 0.01
  n_epochs: 100
  device: cuda
  energy_weight: 1.0
  force_weight: 1.0
  reference: min
  normalize: true
  energy_cutoff: 20.0
  weighting_method: boltzmann
  weighting_temperature: 2000 K
parameters:
  cols:
  - epsilon
  - r_min
  scales:
    epsilon: 10.0
    r_min: 1.0
  limits:
    epsilon:
    - null
    - null
    r_min:
    - 0.0
    - null
attributes:
  cols:
  - alpha
  - beta
  scales:
    alpha: 1.0
    beta: 1.0
  limits:
    alpha:
    - null
    - null
    beta:
    - null
    - null